apiVersion: apps/v1
kind: Deployment
metadata:
  name: fahad-deployment
  labels:
    app: myapp
    type: paractice

spec:
  template:
    metadata:
      # name: nginx
      labels:
        app: myapp
        type: paractice
    spec: 
     containers: 
       - name: nginx
         image: nginx:1.18
  replicas: 6
  selector:
    matchLabels: 
      app: myapp
      type: paractice            

